### ISSUE TITLE
Keeping or deleting obsolete translations

### ISSUE THREAD

**Issue by whatyouhide** [elixir-gettext/gettext#210]
When we are merging an old PO file with a new POT file, we remove all translations in the old PO that don't match anything in the new POT. However, the `msgmerge` tool actually marks them as obsolete:

```po
#~ msgid "hello"
#~ msgstr "ciao"
```

Should we do the same, or are we good with removing them?

\cc @josevalim

**Comment by josevalim** [comment]
@whatyouhide sounds good to me!

**Comment by halostatue** [comment]
It would also be good to consider the `changed` marker if it can be detected:

```
#| msgid "Old Translation Key"
msgid "New Translation Key"
msgstr ""
```
