### ISSUE TITLE
gettext_comment disappearing

### ISSUE THREAD

**Issue by Wijnand** [elixir-gettext/gettext#222]
When using gettext_comment it only appears the first time you extract a msg. 
So for example:

```
    gettext_comment("very important clarifying comment")
    gettext("This is some very awesome text"
```
If you would run gettext.extract the comment does appear in the pot file.
However, if you run extract again the comment is gone.
Only if the string within the gettext call gets updated, and is thus a new msg again, the comment is back in the pot file.

**Comment by whatyouhide** [comment]
Hey @Wijnand, could you provide us with a minimal case that reproduces this? Thank you!

**Comment by Wijnand** [comment]
Hey @whatyouhide I think it can not get any simpler than this:  https://github.com/Wijnand/gettext_comment_missing_bug

At first I wanted to see if I could write a failing test for it but I did not really know where to start.
