### ISSUE TITLE
[Feature] Formatting of multiline strings in the PO and POT files

### ISSUE THREAD

**Issue by Zurga** [elixir-gettext/gettext#229]
At the moment, the multiline strings that represent msgids are concatenated to a single line with newlines inside them when they are dumped to PO and POT files. I can create a pull request that fixes this, with the option to make it a config setting (disabled by default). It would greatly improve readability of the msgids in the PO and POT files. I must say that I do not know how any PO editors treat the msgids in the way they are represented now.

The expected behaviour would be:
```elixir
gettext("""
A string
on more
lines
""")
```
```
msgid: ""
"A string\n"
"on more\n"
"lines"
````
Instead of the current way where it is:
```
msgid: "A string\non more\nlines"
```

**Comment by whatyouhide** [comment]
I can't recall exactly, but isn't

```po
msgid ""
  "A string"
  "on more"
  "lines"
```

equivalent to

```po
mgsid "A stringon morelines"
```

instead?

**Comment by Zurga** [comment]
Yeah you are right. What it should be is:
```
msgid ""
"A string\n"
"on more\n"
"lines"

**Comment by whatyouhide** [comment]
@Zurga I don't know if we should split a string like that automatically. Do we do that anywhere already as far as you know? I can't recall 😄

**Comment by josevalim** [comment]
Given that we need to add \n anyway, I am a bit indifferent on the
approaches. Any is fine with me.
-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D

**Comment by Zurga** [comment]
@whatyouhide No, it does not happen anywhere automatically at the moment. 

I don't think that formatting into multiple strings in the PO file would cause unexpected behavior (on the Gettext side) as the key for a `msgid` is generated by `IO.iodata_to_binary/1` in `lib/gettext/po/translations.ex` on line 109. 

A `msgid` that consists of multiple strings, either delimited by a space or by a newline are added as separate strings in the `msgid` and `msgstr` lists in the Translation struct. This is an excerpt from the `test/po_test.exs`:
```
msgid "indenting and " "strings"
msgstr "indentazione " "e stringhe"
...
%Translation{
msgid: ["indenting and ", "strings"],                                
msgstr: ["indentazione ", "e stringhe"]                              
}
```
When `IO.iodata_to_binary/1` is called on the `Translation.msgid`, it will return "indenting and strings" as binary, so the keys should stay the same if we add a newline and the end of separate strings in the PO files.

**Comment by whatyouhide** [comment]
Honestly I don't really have a preference here either, I'd say if this is a tiny amount of code to make it happen, let's go for it, otherwise I'm not sure it's worth the additional complexity.

**Comment by Wijnand** [comment]
The reason Zurga asked was because I would love this feature and we wanted to sponsor development. However, at the moment we do not have a use-case for it anymore (Phraseapp will butcher the nicely formatted gettext files after syncing back). I am fine with closing this issue

**Comment by josevalim** [comment]
Thanks for the updates. We can always reopen it if someone needs this feature!
