### ISSUE TITLE
Release 0.17.2 has incorrect semantic version, as it causes breakage for Timex v3.6.1

### ISSUE THREAD

**Issue by deepankar-j** [elixir-gettext/gettext#236]
[PR 228](https://github.com/elixir-gettext/gettext/pull/228) causes a breakage for Timex v3.6.1.    That's not necessarily the fault of that PR, but rather the fact that the latest gettext release version is 0.17.2 (a patch version update), when in fact it has a breaking change. 

Timex v3.6.1. works with gettext 0.17.0 (which makes sense given PR 228).  

If this is truly meant to be a patch version, then perhaps lgettext should be updated to support a 4 arity function?  Otherwise, perhaps at least the minor version should be bumped.

Here's the error that I see in Timex.

```
     ** (UndefinedFunctionError) function Timex.Gettext.lgettext/4 is undefined or private
     code: email = create_eco_email(portal_login.person, engineering_change_order)
     stacktrace:
       (timex) Timex.Gettext.lgettext("en", "months_abbr", "Jan", %{})
       (timex) lib/l10n/translator.ex:156: Timex.Translator.get_domain_text/3
       (timex) lib/l10n/translator.ex:123: Timex.Translator.get_months_abbreviated/1
       (timex) lib/format/datetime/formatter.ex:467: Timex.Format.DateTime.Formatter.format_token/6
       (timex) lib/format/datetime/formatters/default.ex:183: Timex.Format.DateTime.Formatters.Default.do_format/4
       (timex) lib/format/datetime/formatter.ex:52: Timex.Format.DateTime.Formatter.lformat!/4
```

**Comment by josevalim** [comment]
Hi @deepankar-j! v0.17.2 did not break semver because `lgettext` was never a public API. So in this case, Timex was using private APIs from gettext and we were in the right of removing. We will push a fix but please submit a patch to Timex so it uses the proper gettext APIs, otherwise it will break in future releases once again.

Thanks for the report!

**Comment by josevalim** [comment]
v0.17.3 is out!

**Comment by deepankar-j** [comment]
Thank you, @josevalim!
