### ISSUE TITLE
Compilation time with many locales

### ISSUE THREAD

**Issue by epilgrim** [elixir-gettext/gettext#238]
In my application, gettext compile takes around 10 minutes in developer's machines (docker inside mac, so i don't expect it to fly. On CI and production it is several minutes, but not as much as 10)
I have around 20 locales with around 6000 strings each, and I will keep adding more, so I need a way to decrease developer's time spent on recompilations.
I'm not as concerned about paying this price on production or CI, but for tests and development, i'm trying to find a way to use less locales.

My first thought was to have a `priv/gettext_dev` folder for development, and the normal `priv/gettext` for production. But that would force me to an extra step each time we run gettext_extract, as it's ran in the development environment, copying the .pot files from one folder to the other.
Second thought is to have a way to restrict the number of locales processed in development environment. Would you accept a PR with a whitelist of locales to compile, so it can be configured per environment?

Do you have any other idea or out of the box solution that i'm missing?

**Comment by wojtekmach** [comment]
Have you tried the [`:one_module_per_locale`](https://hexdocs.pm/gettext/Gettext.html#module-backend-configuration) option? That should help with large projects and many locales.

**Comment by josevalim** [comment]
> Second thought is to have a way to restrict the number of locales processed in development environment. Would you accept a PR with a whitelist of locales to compile, so it can be configured per environment?

Definitely.

Btw, have you tried the `one_module_per_locale` option? I would be curious about the speed ups.

Also, if you give me large .po files, I can also try to bring the time down a bit. I assume there is a good amount of low hanging fruits in the process.

**Comment by epilgrim** [comment]
yeah, I'm already using the one_module_per_locale option. without it it wouldn't even compile in CI because of RAM.
@josevalim I can send you some files privately if you tell me where

**Comment by josevalim** [comment]
@epilgrim you can find my e-mail in my github profile. :)

**Comment by josevalim** [comment]
Closing in favor of the PR!
