### ISSUE TITLE
Provide path information for SyntaxError

### ISSUE THREAD

**Issue by woolfred** [elixir-gettext/gettext#243]
Hello hello,

when having merge conflicts I usually tend to just accept all and then do a `mix gettext.extract --merge` afterwards.

Sometimes it happens that a part is lost (msgid or msgstr) and I get a `SyntaxError`. Currently only the file name is provided like
`(Gettext.PO.SyntaxError) default.po:16: syntax error before:`

When having multiple languages you still don't know which of your .po files is broken. Therefore showing the file path should help you identify the problem easier.

Wouldn't something like this make it easier to spot the problem:
`(Gettext.PO.SyntaxError) priv/gettext/en/LC_MESSAGES/default.po:16: syntax error before: `

Form my understanding the translations are always somwhere in the `priv` folder. Therefore I thought you could simply do something like that in `Gettext.PO.SyntaxError`:
```elixir
defp file_in_priv(file) do
  String.replace(file, ~r/^.*(?=(priv))/, "")
end
```
But as I was looking through the tests this convention isn't used. Have your thought about extracting the relative path somehow?

If we could figure out how to provide the relative path to the problematic file, it would allow better tool support, so we can cmd/ctrl + click on the error and directly jump to correct location.

Cheers!

**Comment by whatyouhide** [comment]
@woolfred thanks for the report! It's interesting because as far as I know we always use the relative path of the file and not just the file name. I'm pretty busy over here, so it would really help if you could provide a minimal reproducing case that reproduces this issue and I'll try to get my hands on fixing it :)

**Comment by whatyouhide** [comment]
Woof, was pretty simple 😄 Thanks @josevalim! 💟

**Comment by woolfred** [comment]
Uff, yes. Could have also tried just that 🙈 Thank you both!
