### ISSUE TITLE
Runtime mode like for plug

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-gettext/gettext#245]
Changing translations does often need to recompile many many modules, which in dev can become quite tedious. I'm wondering if there's the possibility to introduce a runtime mode akin to the one of plug, which can be enabled in development.

**Comment by whatyouhide** [comment]
Can you expand on your use case? The thing that is slow is running `mix gettext.extract`, right? If so, why run it continuously? In any case thanks for the issue @LostKobrakai! 💟

**Comment by josevalim** [comment]
The mechanisms are very distinct. Plug does not actually reduce the amount of code being compiled, it just moves the code to runtime to avoid compile time dependencies. But the amount of work done during compilation is roughly the same.

This won't work for gettext. For gettext, your best option is to reduce the amount of locales being compiled for dev/test. Someone recently added such option, so I recommend using it. :)

**Comment by LostKobrakai** [comment]
I've just two locales (DE/EN), but changing my default.po currently recompiles around 300 modules if updated. What I was wondering if there could be a mode, where the gettext backend calls are no longer macros, but function calls to a single module, which would recompile when translations are updated.

**Comment by josevalim** [comment]
Ah, the issue is not the compilation of locales but rather the callers. Now that Elixir v1.10 ships with compilation tracers, we could actually make them regular functions and use the tracers to find all translations to extract. But that also means you can no longer `import Gettext` and instead you have to use the qualified name, which may not be worth the benefits here.

**Comment by LostKobrakai** [comment]
I was thinking about a switch for what `use Gettext` compiles into the userland module to change macros to functions. Not 100% sure if that would help though.

**Comment by josevalim** [comment]
Doesn't help if you still do `import MyApp.Gettext` whenever you need to use it.
