### ISSUE TITLE
Compile interpolation in gettext_noop

### ISSUE THREAD

**Issue by vermaxik** [elixir-gettext/gettext#247]
Hi,

I have `MyProject.FormValidator` module where I check and collect errors for a form.
And I implement the `Gettext` for errors  with `dgettext_noop` e.g.:
```
defp validate_markets([]) do 
  {:error, dgettext_noop("errors", "Need to pick at least 1 market")}
end
```

And use this validator module in live_view with function method:

```
defp display_error(errors, field) do
  ~E"""
      <span class="form__message form__message--error">
        <%= Gettext.dgettext(Web.Gettext, "errors", Keyword.get(errors, field)) %>
      </span>
  """
end
````
 
Works perfect, but I have few validation errors with interpolation with module attribute:
```
defp validate_markets(markets) when length(markets) > @max_markets do
  {:error, dgettext_noop("errors", "maximum %{max_markets} markets allowed")}
end
```

But unfortunately it not possible to use like this.

Maybe it possible to implement `dgettext_noop/gettext_noop` with dynamic variables like for `Gettext.gettext(Web.Gettext, dynamic_variable)` ? Make sense?

If it possible, I would like to help with it.

Thank you.

**Comment by josevalim** [comment]
I beleive we could make that work, yes. Can you try sending a pull request so we could see how it would look like?

**Comment by vermaxik** [comment]
Yeah, sure,  I'll try 👍

**Comment by vermaxik** [comment]
Hi again,

I spent few evenings on writing possible implementation on this issue, but to be honest it too many macros to me 😄 To implement this feature request, I need more knowledge about macros and deep understanding of this hex package.

I don't want to block anyone to contribute and share test what I tried to achieve: 

```
test "(d)(p)gettext_noop with dynamic context" do
    msgid = "dynamic context %{name}"
    assert Gettext.gettext_noop(Translator, msgid) == msgid
    assert Gettext.dgettext_noop(Translator, "errors", msgid) == msgid
end
```

To have a possibility call this dynamic context:
```
Gettext.dgettext(Translator, "errors", msgid, name: "pass binding")
```

I stuck with `MissingBindingsError`when tried to generate `gettext_noop` with empty binding. 

I would like to handover this to more experience guys, or come back with a time.

**Comment by josevalim** [comment]
Hi @vermaxik! Sorry for the delay on this.

I misunderstood your original request: for me you wanted to pass the bindings to `gettext_noop`, which would be doable, but we can't make `gettext_noop` dynamic because the whole point of `_noop` is to see the string at compilation time, so we can generate `.po` files. Therefore it makes sense you were running into that error, as that is a requirement.

I apologize for sending you down the wrong path. I hope you could at least learn a thing or two about the codebase though. :)

Thank you!

**Comment by johannesE** [comment]
After struggling with a predefined list of strings to be marked for translation at compile time for quite a while, Kip helped me on stackoverflow: https://stackoverflow.com/questions/65869082/marking-list-of-strings-for-translation-with-elixir-gettext-at-compile-time

Do you think the macro could be helpful for others too?
```
  @doc "Marks a list of strings available for translation during compile time"
  defmacro extract_gettext_strings(domain, stringlist) do
    {strings, _} = Code.eval_quoted(stringlist)

    for string <- strings do
      quote do
        MyAppWeb.Gettext.dgettext_noop(unquote(domain), unquote(string))
      end
    end
  end
```

Honestly I still think there should have been an easier solution to that. 😅
