### ISSUE TITLE
Sort output

### ISSUE THREAD

**Issue by egze** [elixir-gettext/gettext#248]
In GNU GetText there are options to sort output: https://www.gnu.org/software/gettext/manual/gettext.html#Output-details-5

Specifically `--sort-output` and `--sort-by-file`.

Right now we have a problem that `mix gettext.extract -- merge` outputs in the order it sees the files on disk (correct me if I'm wrong). And our translation service sorts, there is no option to leave the order as is. This creates a git diff that is unmanageable.

The best course of action for me is that both the `gettext.merge` and our translation service sort identically. Then in diff I would really see what changed.

Is there a way to make `mix gettext.merge` to sort? If not, please give a quick hint where to add it and I will try to tackle it.

**Comment by josevalim** [comment]
A PR that makes it sort would be welcome. We may sort today by file and line and you probably want to sort by id. So I would try to find the current sorting code.

**Comment by egze** [comment]
Yeah, sorting by id is what I need.

These are the options of the service:
```
--export_sort value       
       Key sort order (first_added, last_added, last_updated, 
       a_z, z_a) 
```

**Comment by whatyouhide** [comment]
@egze wasn't this solved by https://github.com/elixir-gettext/gettext/pull/244?

**Comment by josevalim** [comment]
Good call @whatyouhide !
