### ISSUE TITLE
Difficult to access mix tasks docs at hexdoc.pm

### ISSUE THREAD

**Issue by smaximov** [elixir-gettext/gettext#250]
At [hexdocs.pm](https://hexdocs.pm/gettext), click on the "MIX TASKS" section in the sidebar:

![Screenshot from 2020-05-28 11-24-32](https://user-images.githubusercontent.com/1370047/83118028-7d120580-a0d6-11ea-9e4c-b787faf863a3.png)

## Expected behaviour

The list of all mix tasks for gettext is shown.

## Actual behaviour

Nothing happens (aside from modifying the page URL fragment to `full-list`). Also, there's no package version selector.

## Workaround

You can still access mix task docs by navigating to the URL corresponding to a mix task module (eg. [Mix.Tasks.Gettext.Extract](https://hexdocs.pm/gettext/Mix.Tasks.Gettext.Extract.html)).

## Environment

I can reproduce the issue with the following browsers:

* Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
* Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Comment by josevalim** [comment]
@smaximov can you please open up this issue on the ExDoc repo? github.com/elixir-lang/ex_doc

Thank you.
