### ISSUE TITLE
Reusing Gettext.Extractor Merge Infrastructure

### ISSUE THREAD

**Issue by halostatue** [elixir-gettext/gettext#252]
I had to write a custom gettext extractor last night for parsing our JavaScript files (not a single one of the existing mechanisms for parsing JavaScript caught all of my translations; I would consistently be left with about 90% of the strings). Because I’ve been using `msgcat`, `msgmerge`, and `msguniq`, I have all of our JavaScript (Vue) translations merged with our Elixir translations.

In the process of dealing with the extractor, I had to copy large parts of `Gettext.Extractor` functionality that are used for loading and merging existing `pot` files (`Gettext.Extractor/merge_pot_files/3`):

```
    # The following is based on Gettext.Extractor.merge_pot_files/3. This
    # function is public for testing purposes, so I’m not going to call it.
    # This will _merge_ our existing .pot file.
    %{path => :existing}
    |> Map.merge(%{path => po_struct}, &merge_existing_and_extracted/3)
    |> Enum.map(&tag_files(&1))
    |> Enum.reject(&match?({_, {_, :unchanged}}, &1))
    |> Enum.map(&dump_tagged_file/1)
    |> Enum.each(fn {path, podata} ->
      File.write!(path, podata)
      Mix.shell().info("Extracted #{Path.relative_to_cwd(path)}")
    end)
```

This is a modified version of the functionality there, because I already know that the backend `pot` file exists at `path` (`priv/gettext/translations.pot`) and I am not permitting any special configuration (so I removed `gettext_config` parameters). This meant that I needed to copy all of the functions like `merge_existing_and_extracted/4`, `tag_files/2`, `dump_tagged_file/2` and all of the subordinate functions.

I did this because of this:

```elixir
  # Made public for testing.
  @doc false
  def merge_pot_files(po_structs, pot_files, gettext_config) do
```

I believe that this is something that could be made _officially_ public, although it might be better to separate it into something like `Gettext.Extractor.Merge` or `PO.Merge` (I’ve read the discussion in #215 and this feels like it _may_ be something related to that overarching discussion).

(As an aside, I will probably be gisting the JavaScript parsing bits that I did, because they’re pretty good for a regex-based parser.)

**Comment by josevalim** [comment]
I think we can bundle this with #215. It would make total sense to have a library to modify PO files, so we can expose those more. At the moment there is no proper place to put this in Gettext, as it concerns itself mostly with other APIs.

**Comment by halostatue** [comment]
If I weren't completely rekt by having to write a gettext extractor last night and on a tight deadline for some functionality, I would probably volunteer to move some of this code around to make it more officially available for when the split between `PO` and `Gettext` happens. Maybe in a few weeks.

**Comment by josevalim** [comment]
That would be very appreciated! I will close this for now and we can continue it there. :)
