### ISSUE TITLE
Configurable default domain?

### ISSUE THREAD

**Issue by halostatue** [elixir-gettext/gettext#253]
I’ve been working with a couple of different JS implementations of gettext (before rolling a fork of one of them to work better with Vue), and it appears that _most_ JS implementations use `messages` as their default domain—and have an easy way to change the active default domain.

As best as I can tell, this would be set by calling `textdomain(domainname)` in the C version of gettext. What I think would be useful would be providing a `domain` value to `use Gettext`:

```elixir
defmodule MyApp.Gettext do
  use Gettext, otp_app: :my_app, domain: "messages"
end
```

I can work up a PR for this if that makes sense.

**Comment by josevalim** [comment]
Sounds good to me. Let’s call it default_domain though!

**Comment by halostatue** [comment]
Should this be global or per-backend? I’m leaning toward per-backend, but it won’t be hard to make it work like `:default_locale`.

**Comment by halostatue** [comment]
Also, I’m looking at this and assuming that `Gettext.gettext/3` would always use "default", or should it use `dgettext(backend, binding.__gettext__(:default_domain), magic, bindings)`?
