### ISSUE TITLE
Apparent mishandling of reference comments on merge

### ISSUE THREAD

**Issue by halostatue** [elixir-gettext/gettext#255]
What I’m reporting here is not unique to Elixir’s gettext implementation, as I have seen it with some version of `msguniq` from the official GNU tooling, and it may not be a bug, but it feels like one and it results in an unnecessarily large delta.

We ran `mix gettext.merge priv/gettext` and got a diff that looks like this:

```
diff --git a/priv/gettext/en_CA/LC_MESSAGES/translations.po b/priv/gettext/en_CA/LC_MESSAGES/translations.po
index 7b87ad0d..e61885ff 100644
--- a/priv/gettext/en_CA/LC_MESSAGES/translations.po
+++ b/priv/gettext/en_CA/LC_MESSAGES/translations.po
@@ -95,8 +95,7 @@ msgid "Account will expire on %{when}"
 msgstr "Account will expire on %{when}"
 
 #: assets/src/components/common/elements/modal/LinkChargeBuyerModal.vue:26
-#: assets/src/components/common/elements/tables/PurchaseHistoryDetails.vue:24
-#: assets/src/components/common/elements/tables/PurchaseTable.vue:41
+#: assets/src/components/common/elements/tables/PurchaseHistoryDetails.vue:24 assets/src/components/common/elements/tables/PurchaseTable.vue:41
 msgid "Account:"
 msgstr "Account:"
 
```

There are _dozens_ of cases like this. The problem is that it has taken two lines:

```gettext
#: assets/src/components/common/elements/tables/PurchaseHistoryDetails.vue:24
#: assets/src/components/common/elements/tables/PurchaseTable.vue:41
```

And turned them into one long line (much longer than 80 characters):

```gettext
#: assets/src/components/common/elements/tables/PurchaseHistoryDetails.vue:24 assets/src/components/common/elements/tables/PurchaseTable.vue:41
```

This is common enough with what I’ve been dealing with lately (both from the Elixir tools and `msguniq`) that I have a ex-command in my vim history: `:%s/\([^:]\) assets/\1^M#: assets/g` to fix it.

**Comment by halostatue** [comment]
Related, but not _quite_ the same, so I can file this separately if you wish, is that it appears that `#. comment` comments are stripped by the PO handling, but `# comment` comments are not. Ideally, both should be kept.

**Comment by josevalim** [comment]
We should definitely have one `#:` per `file:line`. A PR is welcome.

> but # comment comments are not. Ideally, both should be kept.

We should probably check but I am almost sure one of those are not meant to be kept. We have different kinds of comments (extracted comments, translator comments, template comments) and they have different behaviours.
