### ISSUE TITLE
Translation failure when specifying another priv folder

### ISSUE THREAD

**Issue by StormBytePP** [elixir-gettext/gettext#256]
When using Gettext v0.18.0 and specifying a folder to store the pot and po files via _priv_ attribute, I found that when selected folder is different than priv/* then that domain will fail any translation.

The curious thing is that ```mix gettext.extract``` works as expected, outputing correct data into correct folder.

I uploaded a [minimal example](https://github.com/StormBytePP/elixir-gettext-test) to GitHub to reflect this missbehaviour which can be tested just by running unit tests with:

```bash
mix deps.get && mix test
```
In my honest opinion, it would be interesting to fix this missbehavior to allow better organization for po files.

Thanks.

**Comment by josevalim** [comment]
This is an Elixir/OTP limitation. Only ebin and priv directories are copied to the build directory, which is precisely why the option is named priv.
