### ISSUE TITLE
[Question] Reload PO files at runtime

### ISSUE THREAD

**Issue by nsprod** [elixir-gettext/gettext#257]
Hello all 👋 ,

I'm new to Elixir so first I want apologize in advance if my understanding of the problem I'm facing is not correct.

I'm working on an application that stores translations in a software localization management platform (Transifex, PhraseApp,..). We use their API to download and store the different PO files into the Phoenix `priv` directory (at runtime). Then in our different Phoenix views we get the translation using `Gettext.dgettext(MyApp.Gettext, "app-content", my_translation_key)`. This works well in development thanks to code reloading, now I'm wondering if there is a way to make it work in production 🤔. 

As Gettext needs to compile PO files into Elixir code I don't see how to make it refresh the new PO files I download at runtime. But this would be very convenient as otherwise we have to redeploy our application every time we create / update translation. 

Do you think this is a workflow that could be implemented using the Gettext library?
Maybe using a custom backend?

Thanks 🙂

**Comment by josevalim** [comment]
There is not built-in mechanism for doing this in production. We would need to provide some extra APIs, that allow you to recompile an endpoint, but they do not exist yet.

**Comment by josevalim** [comment]
And welcome!! 👋

**Comment by josevalim** [comment]
Closing this as this is a bigger change. If someone wants to work on it, please let us know!
