### ISSUE TITLE
[Question] Get all keys & values for a single locale

### ISSUE THREAD

**Issue by PatrickSachs** [elixir-gettext/gettext#259]
Is there a way to get all data for a single locale? 

E.g. 
```elixir
1> Gettext.get_all_data("de")
[
  %{
    msgid: "Hello World",
    msgstr: "Hallo Welt"
   },
  # etc...
]
```
(I understand that the actual data structure would be significantly more complex due to pluralization rules, etc...)

A feature like this would be really useful for me, since I'd ideally like to use a single PO file for both strings used in the frontend (Vue JS) as well in backend (Elixir), to not cause confusion among translators and avoid duplicating strings.

The PO file would read by Elixir using Gettext, converted to a JSON format understood by the frontend framework used and then sent via a HTTP request.

Thanks!

**Comment by josevalim** [comment]
We don’t include it in the module and we don’t plan to because this data can be really large. We do have PO parser, it is private, but you can use it as long as you have it in mind. We do plan to make it public, which is what you would use. See #215.
