### ISSUE TITLE
[Question] Using gettext through a dependency in a phx app

### ISSUE THREAD

**Issue by drews256** [elixir-gettext/gettext#260]
I've been exploring Kaffy (https://github.com/aesmail/kaffy) for use as an admin dashboard for applications we work on in house for an assortment of clients.

I really like it and the style but it's a no go if we can't brand it for our clients. One thing that is listed in their issues is to allow the use of i18n by using `gettext`. I started diving into adding `gettext` to Kaffy and realized that it is not straight forward to get `gettext` to extract definitions from Kaffy and have them in the parent application. 

Any thoughts on doing something like this? 

Basically I want `gettext` to find definitions from the dependecy.

Some app that is set up like:
```
defmodule MyApplication.Mixfile do
  use Mix.Project

  def project do
    [
      app: :my_application,
      version: "0.0.1",
      elixir: "~> 1.9",
      elixirc_paths: elixirc_paths(Mix.env()),
      compilers: [:phoenix, :gettext] ++ Mix.compilers(),
      start_permanent: Mix.env() == :prod,
      aliases: aliases(),
      deps: deps(),
    ]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [
      mod: {MyApplication.Application, []},
      extra_applications:
        [:ex_machina, :logger, :runtime_tools, :bamboo, :segment] ++
          env_specific_applications(Mix.env())
    ]
  end

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [
      {:phoenix, "~> 1.5.0"},
      {:ecto_sql, "~> 3.0"},
      {:phoenix_pubsub, "~> 2.0"},
      {:phoenix_ecto, "~> 4.0.0"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.10"},
      {:plug_cowboy, "~> 1.0"},
      {:gettext, "~> 0.11"},
      {:tesla, "~> 1.3.3"},
      {:jason, "~> 1.2.0", override: true},
      {:kaffy, "~> 0.8.0"},
    ] 
  end

  # Aliases are shortcuts or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    [
      "ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
      "ecto.reset": ["ecto.drop", "ecto.setup"],
      test: ["ecto.create --quiet", "ecto.migrate", "test"]
    ]
  end
end
```

and in Kaffy there are a number of templates:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= Kaffy.Utils.title() %> - <%= gettext "Kaffy" %></title>
  </head>
</html>
```

The corresponding .pot files would live in:

```
my_application/priv/gettext/default.pot
```

So we can change up what is rendered by Kaffy from the MyApplication app.

I have taken a look at the `Mix.Tasks.Gettext.Extract` and was pulling apart the `Gettext.Extractor` and Gettext.Extractor.Agent` but wasn't making too much progress. Any thoughts on making this happen? Is this not something you'd do with `gettext`? 

I was looking at `linguist` but the community seems to be moving towards `gettext`.

**Comment by josevalim** [comment]
My suggestion is to make the Gettext path for Kaffy configurable. This way you can tell Kaffy to look at your current application and force it to recompile using pó and pot files from your app. This way you don’t need to mess with the extractor and anything else.

**Comment by drews256** [comment]
Sure, is there a trick to get gettext to pick up the files from Kaffy??

With the above configuration running:

`mix gettext.extract` 

results in basically nothing happening. On a clean phx install it pulls the errors as expected and nothing else.

**Comment by drews256** [comment]
The configuration for Kaffy is set up like:

```
  use Gettext, otp_app: :kaffy, priv: "../../../priv/gettext"
```
