### ISSUE TITLE
[Question] Default bindings to Gettext.dpgettext/5

### ISSUE THREAD

**Issue by rothsberg** [elixir-gettext/gettext#261]
Great work with the support for "particular" translations.

Is there a reason why `Gettext.dpgettext/5` doesn't support default (empty) bindings?

**Comment by whatyouhide** [comment]
No reason, I think it was just left out by accident. Fixed in https://github.com/elixir-gettext/gettext/commit/b7d8fb58f93cdd3aa2418ed1f350d1b63deeb123 :)
