### ISSUE TITLE
Support for live translation in Live View

### ISSUE THREAD

**Issue by sanjibukai** [elixir-gettext/gettext#263]
Hello,

Currently, if we have a `gettext "Hello World"` in a LiveView view, it's not sufficient to have the translated text updated in live since there is nothing changing in the context of the LiveView.

I ended up using something like that:
```elixir
# in the view
<%= @x && gettext "Hello World" %>

# in the liveview
def handle_event("set_en", _, socket) do
  Gettext.put_locale(MyApp.Gettext, "en")
  {:noreply, force_rerender(socket)}
end
defp force_rerender(socket, fingerprint \\ :x) do
  update(socket, fingerprint, &(&1 + 1))
end
# x being liek a fingerprint and defined in mount()
```
Now I wanted to make that mechanism with the lesser code possible..
But if we want to benefit from the extractor, we can't define a custom function like:
```elixir
# in the view
lgettext(@x, "Hello World")`

# in the liveview
def lgettext(x, text) do
  x && gettext(text)
end
```
But since I am unable [to define a macro](https://elixirforum.com/t/how-to-return-literals-with-macros/34274/12?u=sanjibukai) to do that work, I'm asking here and I think of three possible solution:

- The first one (the one I would do in ruby) but I'm not sure if it's possible to do it in Elixir (I tried but I failed with the error `conflicts with local function`) would be function overloading.. And simply redefining the function. The extractor would still "see" the correct function calls. This adds the benefit of supporting every flavor of `gettext` (`dgettext`, `ngettext` etc.)

- The second one is to define a custom function (renamed like `lgettext`) and being able to configure the extractor by adding that function. Besides defining an option for the extractor (parser?) this solution change nothing else.
I tried to search where this is done in the codebase, but I cannot find where the extractor grab that list and do its work.

- The third solution, might be to simply add an arbitrary keyword option that doesn't do anything, but in this way it will trigger the rerendering of the liveview.
This solution might be the worse since it will modify the API.

Of course it's also possible to solve this issue from the Phoenix side. Like for example by having some kind of `force_rerender(socket)` function ([discussed here](https://elixirforum.com/t/how-to-return-literals-with-macros/34274)).

I'm aware that this is an XY problem and the correct behavior might be to have that API in Phoenix that could rerender at will.
But I'm more asking in order to learn (like the macro thing asked on the elixir forum) rather than really adding that somehow broken support in this `elixir-gettext` repo.

Anyway, if all of this doesn't really make sense. Feel free to close and move on..

Thank you very much.

**Comment by josevalim** [comment]
Hi @sanjibukai! I think in this case, since change the locale is something rather rare, could you invoke a live_redirect, forcing the current page to be fully reloaded?

Those events should be really rare, so I really wouldn't try to optimize for them.

**Comment by sanjibukai** [comment]
Hey @josevalim!

Fair enough!
As I stated I went this path more for learning purpose rather than ending up in an adopted implementation.
I'm closing this issue..
Thanks for taking the time to answer!

But because it's you and I couldn't find a better person to ask..
Is it possible to use Elixir Macro like how the #define preprocessor works in C.
I mean pure text interpolation and replacement:
```
# Replacing
lgettext("HelloWorld")
# by
@x && gettext("hello World")
```
Since it will be used in a view where `@x` is available, I thought a solution could exist.

The following:
```
defmacro lgettext(expr) do
  quote do
    @x && unquote(expr)
end
```
is not working since it claims for `@x` at this declaration scope.
I even tried the two following:
```
defmacro lgettext(expr) do
  {:@, [context: Elixir, import: Kernel], [{:x, [context: Elixir], Elixir}]} && expr
end

defmacro lgettext(expr) do
  quote do
    @x && unquote(expr)
  end
end
```
I guess that if `@x` was a regular variable that last one would have worked.
I also tried accessing assign variable through the regular `socket.assigns` variables but without success..

Feel free to ignore if you don't find those questions relevant..
