### ISSUE TITLE
Unhelpful helptext for UnknownLocaleError in mix gettext.merge

### ISSUE THREAD

**Issue by mikl** [elixir-gettext/gettext#264]
So I was trying to generate .po files for Swiss German by running `mix gettext.merge priv/gettext --locale=gsw_CH`. This errors, as the pluraliser does not know of `gsw`.

However, the error is misleading, it says:

```
20:39:42.885 [error] Task #PID<0.183.0> started from #PID<0.94.0> terminating
** (Gettext.Plural.UnknownLocaleError) unknown locale "gsw". If this is a locale you need to handle,
consider using a custom pluralizer module instead of the default
Gettext.Plural. You can read more about this on the Gettext docs at
https://hexdocs.pm/gettext/Gettext.Plural.html
```

If you read the text, and do as suggested, by creating a custom pluralizer, the problem persists. As already discussed in #179, the custom pluralizer does not work when running `mix gettext.merge`.

So the error message is downright misleading. I just spent quite a while banging my head on this wall.

As it turns out, simply specifying the number of plural forms works, like this:

`mix gettext.merge priv/gettext --locale=gsw_CH --plural-forms=2`

I think that either the error message should be changed, or there should be a fallback value (as also mentioned in #179), just my two rappen.

**Comment by josevalim** [comment]
Can you please send a PR that improves the error message? It will at least help avoid others running into it. Thank you!
