### ISSUE TITLE
Bindings interpolation with string keys

### ISSUE THREAD

**Issue by kpanic** [elixir-gettext/gettext#266]
Hello everyone, I was wondering if it would be possible to have bindings in this format:

```elixir
interpolatable = Interpolation.to_interpolatable("%{a} %{b} %{c}")

assert Interpolation.interpolate(interpolatable, %{"a" => 1, "b" => :two, "c" => "thr ee"},) ==
               {:ok, "1 two thr ee"}

```

If not, is there a technical reason?

Thanks for the library!

**Comment by josevalim** [comment]
It should be possible but can you tell us a bit more about your use case?

**Comment by kpanic** [comment]
In my use case we have dynamic translations (that can be updated in time)
AFAIK in the current `interpolate/2` function only supports map with atom keys and I have to convert strings to atoms risking that the atom table will grow and crash the BEAM

**Comment by josevalim** [comment]
@kpanic the string is dynamic but the map you pass to it is known upfront, right?

**Comment by kpanic** [comment]
No, in our use case we can't. The map can be dynamic (from user input/spefication)

**Comment by josevalim** [comment]
Closing in favor of PR discussion.
