### ISSUE TITLE
Very high memory usage with elixir 1.11

### ISSUE THREAD

**Issue by epilgrim** [elixir-gettext/gettext#268]
I have a project with 5145 msgids translated into 28 locales.
Compiling a new project (mix new) with elixir 1.10.1 and just those translations takes around 3GB of memory, and around 2 minutes to compile.

Trying to compile the same project in elixir 1.11.1, I haven't been able to compile it. I've seen the memory reaching 30GB (I have 16GB physical memory... and then going to swap) and after 15 minutes I had to stop it.

Do you have any pointers as to where to start looking for the problem?

**Comment by josevalim** [comment]
To confirm, that’s with the same OTP version, Right? Are you using any flags like one_module_per_locale that generally speed up compilation? Have you tried them out?

**Comment by epilgrim** [comment]
using one module per locale, yes.
good point with the otp version. one was otp 22 and the other 23.
I'll test just changing elixir and report back.
if the problem persists I'll set up a reproduction repo

**Comment by josevalim** [comment]
Yes, please try both only changing OTP versions and only changing Elixir versions. Also try 23.1 as it has some improvements.

**Comment by epilgrim** [comment]
It indeed seems to be erlang 23.1.1.

The compilation finishes with
erlang 22.2.7 elixir 1.10.1
and 
erlang 22.2.7 elixir 1.11.1

But I couldn't finish because of the amount of RAM with
erlang 23.1.1 elixir 1.10.1
and
erlang 23.1.1 elixir 1.11.1

I've set up a reproduction repo with some dummy translations here:
https://github.com/epilgrim/mix-playground/tree/issue/gettext-memory-usage-with-erlang-23

**Comment by josevalim** [comment]
I could verify that each lcoale went from from 23s to 32s on average when updating OTP. 

I proposed some fixes here: https://github.com/erlang/otp/pull/2837 and https://github.com/erlang/otp/pull/2834

The first in particular decreases memory usage considerably in at least half on its peak but about 4 times generally. Furthermore, those patches plus JIT makes everything faster than 22.1 when running on OTP master (roughly 18s on my machine).

There is still the option of compiling those modules per domain, which would be a gettext specific improvement.

**Comment by josevalim** [comment]
I pushed a feature that splits the modules per locale and per domain. Your example app now finishes in 2min56s in my machine (I am using 24+jit) and in 2min26s with my patches above.

In any case, I think you should hold off upgrading to 23 for now. It may be worth using the new feature on gettext master, because I think it will speed your OTP 22 compilation.

**Comment by epilgrim** [comment]
This is AWESOME Jose!! thank you very much.

The way of splitting the compile per domain was my next idea if there was nothing to do with the memory usage! thanks for implementing it :)

If you don't mind me asking, do you have any pointer to blog post or book with content about your thought process and tools to identify the root cause of the memory problems? Would love to understand that a bit more, so next time I can come closer to provide solutions rather than problems

**Comment by josevalim** [comment]
So compiler problems are usually nice to debug thanks to the Erlang/OTP tooling. I usually start with this on Elixir v1.11:

```
$ mix compile --force --profile time
```

That will point me to which file is slow (or if it is the group pass). The next step is to break down why it is slow. You have two options here, one is to execute the Elixir file with the `time` option:

```elixir
$ ERL_COMPILER_OPTIONS=time mix compile lib/problematic_file.ex
```

You will typically see two or three reports like this:

```
core             :  0.653 s   72136.4 kB
sys_core_fold    :  0.482 s   69055.3 kB
sys_core_alias   :  0.146 s   69055.3 kB
core_transforms  :  0.000 s   69055.3 kB
sys_core_bsm     :  0.098 s   69055.3 kB
v3_kernel        :  2.250 s  169439.0 kB
```

It contains all of the Erlang passes, how long time and how much memory they took. The reports are in this order:

1. The first report is for the file (may be absent)
2. The second report is for the body of the module you are defining
3. The third report is for compiling the module itself (the .beam file)

1 is almost never an issue. 2 may be an issue, especially when you have large module bodies doing tons of meta-programming (like the Phoenix router). In your case, compiling the module itself was the slow one, so it was option 3.

Luckily scenario 3 is also the easiest to debug. First step is to [decompile](https://github.com/michalmuskala/decompile) it:

```
$ mix compile NameOfTheProblematicModule --to erl
```

That will emit an Erlang `.erl`. You have to clean it a little bit and then it should be compilable by itself with `erlc`. At this moment, we are out of Elixir lang and into Erlang lang. So next I compile it again with the `-time` flag:

```
$ erlc +time NameOfTheProblematicModule.erl
```

That will emit the same report as above. Now, if the regression is relation to a previous Erlang version, I compare the `+time` reports between Erlang versions to see what got slower.

Once you identified one particular pass that is slower, you can now profile it:

```
$ erlc +'{eprof, PASS}' NameOfTheProblematicModule.erl
```

where `PASS` is the name of the pass, such as `core`, `sys_core_alias`, etc. Now you have to dig into the code and see if there are possible optimizations around it.

**Comment by epilgrim** [comment]
Very interesting write up! Thank you Jose!!
