### ISSUE TITLE
Flags not preserved when merging PO

### ISSUE THREAD

**Issue by maennchen** [elixir-gettext/gettext#282]
## Steps to Reproduce

* Create POT
* Merge File to PO
* Translate Entry and mark as `fuzzy`
* Merge File to PO again

## Expected

Entry is still `fuzzy` 

## Actual

Entry is no longer `fuzzy`

## Why?

We mark translations as fuzzy, when they were translated by a machine and not a person to make sure it will be checked again & maybe corrected.

**Comment by josevalim** [comment]
Closing in favor of PR!
