### ISSUE TITLE
Allow runtime default

### ISSUE THREAD

**Issue by stoyle** [elixir-gettext/gettext#284]
We currently deploy to two national sites, same binary, but different languages.

It would be really nice to be able to set a default at runtime, i.e. via gettext config. What we have to do today, is whenever we start a process, explicitly call `Gettext.put_locale(CountrySettings.language())`. We have found a few good places to default this in phoenix, however there are of course so many ways and places we start processes, that we often forget, leading to translation errors.

Will be happy to contribute some code, if such a feature is welcome.

**Comment by josevalim** [comment]
You can set `config :gettext, default_locale: language` in your config/runtime.exs and that will apply at runtime. IF you are not on a recent Elixir version, then you can do `Application.put_env(:gettext, :default_locale, language)` on the application start callback.

**Comment by stoyle** [comment]
Wow, thanks! How on earth did we miss this... Seems to work perfectly.
