### ISSUE TITLE
Interpolation Bindings as map

### ISSUE THREAD

**Issue by maennchen** [elixir-gettext/gettext#293]
## Problem

Currently, `bindings` can only be specified as key/value pairs (map/keyword list).

For some interpolation formats, it might not make sense to have key-value pairs. One example for that would be `printf` based formats.

## Example

I have (as a test of this new feature) built a small library to test it properly from the outside. https://github.com/jshmrtn/gettext_printf

As you can see in the tests, the following code is not possible: https://github.com/jshmrtn/gettext_printf/blob/2a58846d5d909a32637e11f8b8a8229b4eee690a/test/gettext_printf_test.exs#L15

```elixir
      assert "01-11-2021 date (runtime)" ==
               gettext("%02d-%02d-%04d date (runtime)", [1, 11, 2021])
```

Instead, I had to solve it like this:

```elixir
      assert "01-11-2021 date (runtime)" ==
               gettext("%02d-%02d-%04d date (runtime)", %{bindings: [1, 11, 2021]})
```

## Proposed solution

I would like to make the following changes:

* Interpolation modules specify an optional callback `kv_binding_pairs?/0` (default: `true`)
  - If `true`, everything stays as is
  - If `false`
    * anything can be passed as `bindings` and the interpolation module must validate it
    * for plural translations, the binding `count` is not added and the user of the library has to add it manually to the bindings

## Alternate Solutions

* Add specific support for bindings as lists (I don't like this because it restricts interpolations in what they can take as a binding)
* No change (bindings would have to be wrapped in a kv pair; I don't like this because if puts the problem to the user)

## PR

No matter what solution is preferred, I'll happily provide a PR.

**Comment by josevalim** [comment]
Do you have an actual use case for this? Printf based formats _are not_ a good fit for Gettext, because they are order based and stuff like dates change per locale. So unless there is a strong use case for this, this is a strong no for me and if someone really needs, they can go with the bindings (or maybe call it args) approach that you mentioned above .

**Comment by josevalim** [comment]
Alright, given I have a strong preference to key-based formats, and anything order based is asking for troubles, I don't  believe we should support this officially. And you have provided excellent fallbacks if someone really needs it. Thanks!
