### ISSUE TITLE
Uniq comments from gettext_comment/1 for the same translation (on extraction)

### ISSUE THREAD

**Issue by gabrielgiordan** [elixir-gettext/gettext#308]
Hello! First, thanks to all contributors, the lib is awesome.

So, I'm using gettext inside an umbrella project, where 2 apps are using the same gettext module.

Inside the project, each app uses the same translation repeatedly in different places, for example, a call for `dgettext("errors", "App is outdated")` on app 1 and app 2.

I would like to add only one comment for this translation, but `gettext_comment/1` adds a new comment for each of its call.

How should I deal with it? Should I put `gettext_comment/1` on some kind of central place, perhaps inside the own gettext module?

Something like `dgettext_comment("some comment", "errors", "App is outdated")` would be helpful in this case

I tried to add the comment `#.` directly on the `.pot` file as well, but the `mix gettext.extract` task overrides it.

**Comment by whatyouhide** [comment]
Hey @gabrielgiordan, good catch and thanks for the report! 💟 

We should support this at the library level. When doing the extraction, we should `uniq` the comments for a given translation.

Wanna take a stab at a PR? 🙃

**Comment by gabrielgiordan** [comment]
Sure, let me take a look 🙂

**Comment by whatyouhide** [comment]
Closed via #309.
