### ISSUE TITLE
Sort messages alphabetically case insensitive

### ISSUE THREAD

**Issue by superruzafa** [elixir-gettext/gettext#325]
## Problem

Hi!

In my company we use an external tool to do translations. This tool sorts the messages by msgid alphabetically. The problem is that we use keys instead of English messages as msgid. Those keys include uppercase characters.

When extracting messages and `sort_by_msgid` flag to true, the keys are sorted alphabetically but the ones in uppercase are placed before the others, which causes us a lot of headaches.

## Proposed solution

Add another flag `sort_by_msgid_case_insensitive` to use a case insensitive comparation when extracting keys.

## PR

#326

**Comment by whatyouhide** [comment]
Closing in favor of the PR (#326).
