### ISSUE TITLE
`gettext.merge` FunctionClauseError

### ISSUE THREAD

**Issue by maennchen** [elixir-gettext/gettext#355]
_Follow up from @woylie in https://github.com/elixir-gettext/gettext/issues/351#issuecomment-1429531773_

> I just set up a pristine Phoenix 1.7-rc.2 application with Gettext 0.22.0.
> 
> I noticed two other issues.
> 
> - `mix gettext.merge priv/gettext --locale ja` and `mix gettext.extract --merge`
>   will create new `.po` files without the `plural=<rule>`, causing a warning.
> - Running either of those commands when there are `.pot` files without messages
>   causes a FunctionClauseError (I noticed because I generated the Phoenix app
>   with the `--no-ecto` flag, which produces an `errors.pot` without messages).
> 
> ```
> ** (FunctionClauseError) no function clause matching in Expo.PO.Composer.dump_kw_and_strings/3
> 
>     The following arguments were given to Expo.PO.Composer.dump_kw_and_strings/3:
> 
>         # 1
>         "msgstr"
> 
>         # 2
>         []
> 
>         # 3
>         []
> 
>     Attempted function clauses (showing 1 out of 1):
> 
>         defp dump_kw_and_strings(keyword, [first | rest], line_prefix)
> 
>     (expo 0.3.0) lib/expo/po/composer.ex:88: Expo.PO.Composer.dump_kw_and_strings/3
>     (expo 0.3.0) lib/expo/po/composer.ex:36: Expo.PO.Composer.dump_message/1
>     (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
>     (expo 0.3.0) lib/expo/po/composer.ex:21: Expo.PO.Composer.dump_messages/1
>     (gettext 0.22.0) lib/gettext/extractor.ex:240: Gettext.Extractor.merge_or_unchanged/3
>     (gettext 0.22.0) lib/gettext/extractor.ex:267: Gettext.Extractor.tag_files/2
>     (elixir 1.14.2) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
>     (stdlib 4.1.1) maps.erl:411: :maps.fold_1/3
> ```
> 
> I fixed both by updating the plural form headers as suggested and by deleting
`errors.pot`.
> 
> What remains is the `Gettext.PluralFormError`, which you can see by starting the server and opening `http://localhost:4000`. The error disappears after
> downgrading Gettext to 0.21.0. [Here's the demo.](https://github.com/woylie/gettext-plural-forms-error)

**Comment by maennchen** [comment]
@woylie I have a hard time reproducing the `FunctionClauseError` from your comment.

I tried:

```console
git clone git@github.com:woylie/gettext-plural-forms-error.git
cd gettext-plural-forms-error
rm -rf priv/gettext
mix deps.get
mix gettext.extract --merge
mix gettext.merge --locale en priv/gettext
mix gettext.merge --locale ja priv/gettext
```

**Comment by woylie** [comment]
Sorry, my repo doesn't reproduce that error. You can reproduce it by adding a `.pot` file without any `msgid`/`msgstr` pairs.

Creating a new Phoenix app with the `--no-ecto` flag will produce an `errors.pot` file with only this content:

```
mix archive.install hex phx_new 1.7.0-rc.3 --force
mix phx.new gtnfc --no-ecto
cd gtnfc
mix gettext.extract --merge
```

```
## This is a PO Template file.
##
## `msgid`s here are often extracted from source code.
## Add new translations manually only if they're dynamic
## translations that can't be statically extracted.
##
## Run `mix gettext.extract` to bring this file up to
## date. Leave `msgstr`s empty as changing them here has no
## effect: edit them in PO (`.po`) files instead.
```

**Comment by maennchen** [comment]
@woylie I can reproduce it, thanks :)

**Comment by maennchen** [comment]
Fix in https://github.com/elixir-gettext/expo/pull/104, closing.
