### ISSUE TITLE
Interpolation option set but not working

### ISSUE THREAD

**Issue by tommasop** [elixir-gettext/gettext#371]
This configuration

```
config :elixir_boilerplate, ElixirBoilerplate.Gettext, priv: "priv/null", interpolation: ElixirBoilerplate.GettextInterpolation

```

works with:

- Erlang 25.2
- Elixir 1.14

does not work with:

- Erlang 26.0
- Elixir 1.15

You can use this repo https://github.com/mirego/elixir-boilerplate to test it

Be aware that with Erlang 26.0 you also need to add

```
      {:ssl_verify_fun, "1.1.7"},

```

to `mix.exs`

**Comment by whatyouhide** [comment]
Hi @tommasop, thanks for the report and thank you for including a reproducing example.

What should I run in the example repo you gave to reproduce the error? That is, what do you mean by "works" and "not works"?

**Comment by tommasop** [comment]
Sorry @whatyouhide, my bad!

You need to run `mix test`.

With Erlang 25.2 Elixir 1.14 all tests will pass because the `test.exs` configuration 

```
config :elixir_boilerplate, ElixirBoilerplate.Gettext, priv: "priv/null", interpolation: ElixirBoilerplate.GettextInterpolation
```

works correctly thus using  `ElixirBoilerplate.GettextInterpolation` instead of `Gettext.Interpolation.Default`

with Erlang 26.0 Elixir 1.15 at compile time the interpolation option is set correctly but the corresponding test is failing because is using `Gettext.Interpolation.Default` instead of `ElixirBoilerplate.GettextInterpolation`.

Sorry again for my bad reporting and let me know if I can help.

**Comment by maennchen** [comment]
@tommasop Have you solved this in the meantime?

I just cloned the repo and do not have any issues with the mentioned test.

**Comment by whatyouhide** [comment]
Closing this since we haven't heard back for a month. If this pops up again, feel free to comment down here and we can re-open and investigate. Thanks all! 💟
