### ISSUE TITLE
compile depend excoveralls - origin/httpc failed

### ISSUE THREAD

**Issue by bighunter513** [elixir-gettext/gettext#374]
when I add deps timex, 
it depends on gettext,  and failed get sub-depends for excoveralls.git 

===> Upgrading timex v3.7.11
===> Upgrading combine v0.10.0
===> Upgrading gettext v0.23.0
===> Compiling gettext
* Getting excoveralls (https://github.com/whatyouhide/excoveralls.git - origin/httpc)
remote: Enumerating objects: 3266, done.
remote: Counting objects: 100% (444/444), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 3266 (delta 253), reused 347 (delta 185), pack-reused 2822
error: pathspec 'origin/httpc' did not match any file(s) known to git
** (Mix) Command "git --git-dir=.git checkout --quiet origin/httpc" failed
===> sh(mix deps.get)
failed with return code 1 and the following output:
* Getting excoveralls (https://github.com/whatyouhide/excoveralls.git - origin/httpc)
remote: Enumerating objects: 3266, done.
remote: Counting objects: 100% (444/444), done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 3266 (delta 253), reused 347 (delta 185), pack-reused 2822
error: pathspec 'origin/httpc' did not match any file(s) known to git
** (Mix) Command "**git --git-dir=.git checkout --quiet origin/httpc**" failed

**Comment by whatyouhide** [comment]
Fixed in v0.23.1, which I just published 🙃 Thanks for the report! 🙏
