### ISSUE TITLE
Add `Gettext.example` macro

### ISSUE THREAD

**Issue by dkuku** [elixir-gettext/gettext#375]
I have to maintain some pretty complicated strings and translators often reach out to get better context:
for example:
`%{date_time} %{service} for %{first_name} %{with_performing_staff} booked by %{booker_first_name} %{at_location_name}`
This is interpolated to `7:00pm 10 May dinner for Alice with Bob booked by Celine at Doom Edge`
It's even hard for me to know what will be generated without looking at the test module and see how it looks like after interpolation.

My proposal is to a `example` or `comment_example` macro similar to existing `comment` but it will receive a keyword list with the bindings and it will add a comment to the po file with the actual text.

Even better if this could be configured globally where I would create example bindings and this would generate examples before every string, when a binding is missing then it can log a warning.

**Comment by dkuku** [comment]
Adding the available assigns in the comment may be also a good option. Sometimes there is an assign that is not used in English but is still available and may be required in other language.

**Comment by whatyouhide** [comment]
@dkuku thanks for the feature request. Do you know if GNU Gettext provides anything like this? cc @maennchen

**Comment by dkuku** [comment]
I'm afraid this is not supported by gettext

**Comment by whatyouhide** [comment]
Gotcha! Then, for now I'd prefer to keep things simple and keep this closer to GNU Gettext. You can still achieve something very close to this with the `comment` macro. Post 1.0 of Gettext we might revisit this, but for now we really don't have the bandwidth to address this. Thanks for the proposal! 💟
