### ISSUE TITLE
`expo.msguniq` merges translations with different plurals

### ISSUE THREAD

**Issue by alexanderttalvarez** [elixir-gettext/gettext#384]
In version 0.24.0, the `expo.msguniq` command is merging translations with different plurals. For example, let's consider the following case:

```po
msgid "1 review"
msgid_plural "%{reviews_count} of %{reviews_total} reviews"
msgstr[0] "1 opinión"
msgstr[1] "%{reviews_count} de %{reviews_total} opiniones"

msgid "1 review"
msgid_plural "%{reviews_showing} reviews of %{reviews_total}"
msgstr[0] "1 opinión"
msgstr[1] "%{reviews_showing} opinones sobre %{reviews_total}"
```

After using the command, it generates:

```po
msgid "1 review"
msgid_plural "%{reviews_total} reviews"
msgstr[0] "1 opinión"
msgstr[1] "%{reviews_total} opiniones"
```

We are losing one translation.

It's not possible to use `mix gettext.extract` either. It produces an error:
`found duplicate on line 169 for msgid: '1 review' and msgid_plural: '%{reviews_count} of %{reviews_total} reviews'`

Which is not true, because the plurals are different. Only the msgid is the same.

Is that a bug?
Thanks.

**Comment by maennchen** [comment]
@whatyouhide I'm temporarily pining this issue since more people could stumble upon this when updating.

**Comment by alexanderttalvarez** [comment]
Ok, I understand now. Thanks for your explanation 😃. We'll have to find a way to addapt our translations.

I'm closing the issue then.
