### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by BradS2S** [elixir-gettext/gettext#404]
Examples use the format: MyApp.Gettext

Since Phoenix generator automatically puts it here: **MyAppWeb.Gettext**, does it make sense to make that documentation change throughout?

**Comment by whatyouhide** [comment]
No, it does not. Gettext is not tied to Phoenix in any way in and of itself, it's Phoenix which depends on Gettext. To avoid confusion, we can rename `MyApp` to something else but we shouldn't mention "web". Is this actually confusing though?

**Comment by BradS2S** [comment]
That's what I figured. It makes sense that the documentation can't be tightly coupled with just one framework. 

Here's what I ran across specifically that I suspect will grow more common with the deprecation warning:

If you happen to be using Phoenix, and you change `use Gettext, otp_app: ...` to     `use Gettext.Backend, otp_app: :my_app`, you also have to change `import MyAppWeb.Gettext` in **lib/my_app_web/components/core_components.ex**.

Since the deprecation warming says:

```
Then, instead of importing your backend, call this in your module:

    use Gettext, backend: MyApp.Gettext
```

I was copying it from the warning code and then just changing the "MyApp" part and leaving the "Web" omitted because I wasn't super confident I knew exactly what the change did so it took me a sec to realize my mistake. Not a big deal I just wanted to mention it because I ran across [someone else](https://elixirforum.com/t/warning-gettext-first-create-app-create-ecto/65932) that might have also been confused. 

I'm wildly unfamiliar with what is best practices so I don't know if a note in the warning that mentions if you are using the Phoenix framework, you also need to change that other line in **core_components.ex** or it could be a more helpful compile time error that could be implemented in Phoenix since Gettext isn't tied to Phoenix.

Either way I found it interesting.

**Comment by maennchen** [comment]
If we’re doing that, we should also use the correct otp app instead of my_app.

**Comment by BradS2S** [comment]
Yeah happy to try thatSent from my iPhoneOn Dec 6, 2024, at 1:17 AM, Andrea Leopardi ***@***.***> wrote:﻿
We can improve the warning (in Gettext) to use the actual module name, which would fix this issue. How does that sound? Want to give it a try?

**Comment by BradS2S** [comment]
https://github.com/elixir-gettext/gettext/pull/406
